class Data:
    lines = {}
    name = b""
    summ = 0

    def calc_summ(self):
        summ = 0
        addr = 0x2201
        for i in self.lines:
            addr += len(self.lines[i]) + 5
            line = addr.to_bytes(2, "little") + \
                i.to_bytes(2, "little") + self.lines[i]
            for j in line:
                summ += j
        self.summ = summ & 0xffff


to_basic = {0x80: "CLS",
            0x81: "FOR",
            0x82: "NEXT",
            0x83: "DATA",
            0x84: "INPUT",
            0x85: "DIM",
            0x86: "READ",
            0x87: "CUR",
            0x88: "GOTO",
            0x89: "RUN",
            0x8A: "IF",
            0x8B: "RESTORE",
            0x8C: "GOSUB",
            0x8D: "RETURN",
            0x8E: "REM",
            0x8F: "STOP",
            0x90: "OUT",
            0x91: "ON",
            0x92: "PLOT",
            0x93: "LINE",
            0x94: "POKE",
            0x95: "PRINT",
            0x96: "DEF",
            0x97: "CONT",
            0x98: "LIST",
            0x99: "CLEAR",
            0x9A: "MLOAD",
            0x9B: "MSAVE",
            0x9C: "NEW",
            0x9D: "TAB(",
            0x9E: "TO",
            0x9F: "SPC(",
            0xA0: "FN",
            0xA1: "THEN",
            0xA2: "NOT",
            0xA3: "STEP",
            0xA4: "+",
            0xA5: "-",
            0xA6: "*",
            0xA7: "/",
            0xA8: "^",
            0xA9: "AND",
            0xAA: "OR",
            0xAB: ">",
            0xAC: "=",
            0xAD: "<",
            0xAE: "SGN",
            0xAF: "INT",
            0xB0: "ABS",
            0xB1: "USR",
            0xB2: "FRE",
            0xB3: "INP",
            0xB4: "POS",
            0xB5: "SQR",
            0xB6: "RND",
            0xB7: "LOG",
            0xB8: "EXP",
            0xB9: "COS",
            0xBA: "SIN",
            0xBB: "TAN",
            0xBC: "ATN",
            0xBD: "PEEK",
            0xBE: "LEN",
            0xBF: "STR$",
            0xC0: "VAL",
            0xC1: "ASC",
            0xC2: "CHR$",
            0xC3: "LEFT$",
            0xC4: "RIGHT$",
            0xC5: "MID$",
            0xC6: "SCREEN$(",
            0xC7: "INKEY$",
            0xC8: "AT",
            0xC9: "&",
            0xCA: "BEEP",
            0xCB: "PAUSE",
            0xCC: "VERIFY",
            0xCD: "HOME",
            0xCE: "EDIT",
            0xCF: "DELETE",
            0xD0: "MERGE",
            0xD1: "AUTO",
            0xD2: "HIMEM",
            0xD3: "@",
            0xD4: "ASN",
            0xD5: "ADDR",
            0xD6: "PI",
            0xD7: "RENUM",
            0xD8: "ACS",
            0xD9: "LG",
            0xDA: "LPRINT",
            0xDB: "LLIST"}


from_basic = {v: k for k, v in to_basic.items()}

to_koi7 = {"▘": 0x01,
           "▝": 0x02,
           "▀": 0x03,
           "▗": 0x04,
           "▚": 0x05,
           "▐": 0x06,
           "▜": 0x07,
           "🧍": 0x09,
           "↑": 0x0b,
           "\n": 0x0d,
           "→": 0x0e,
           "↓": 0x0f,
           "▖": 0x10,
           "▌": 0x11,
           "▞": 0x12,
           "▛": 0x13,
           "▄": 0x14,
           "▙": 0x15,
           "▟": 0x16,
           "█": 0x17,
           "|": 0x1b,
           "—": 0x1c,
           "←": 0x1d,
           "🍏": 0x1e,
           " ": 0x20,
           "!": 0x21,
           '"': 0x22,
           "#": 0x23,
           "$": 0x24,
           "%": 0x25,
           "&": 0x26,
           "'": 0x27,
           "(": 0x28,
           ")": 0x29,
           "*": 0x2a,
           "+": 0x2b,
           ",": 0x2c,
           "-": 0x2d,
           ".": 0x2e,
           "/": 0x2f,
           "0": 0x30,
           "1": 0x31,
           "2": 0x32,
           "3": 0x33,
           "4": 0x34,
           "5": 0x35,
           "6": 0x36,
           "7": 0x37,
           "8": 0x38,
           "9": 0x39,
           ":": 0x3a,
           ";": 0x3b,
           "<": 0x3c,
           "=": 0x3d,
           ">": 0x3e,
           "?": 0x3f,
           "@": 0x40,
           "A": 0x41,
           "B": 0x42,
           "C": 0x43,
           "D": 0x44,
           "E": 0x45,
           "F": 0x46,
           "G": 0x47,
           "H": 0x48,
           "I": 0x49,
           "J": 0x4a,
           "K": 0x4b,
           "L": 0x4c,
           "M": 0x4d,
           "N": 0x4e,
           "O": 0x4f,
           "P": 0x50,
           "Q": 0x51,
           "R": 0x52,
           "S": 0x53,
           "T": 0x54,
           "U": 0x55,
           "V": 0x56,
           "W": 0x57,
           "X": 0x58,
           "Y": 0x59,
           "Z": 0x5a,
           "[": 0x5b,
           "\\": 0x5c,
           "]": 0x5d,
           "^": 0x5e,
           "_": 0x5f,
           "Ю": 0x60,
           "А": 0x61,
           "Б": 0x62,
           "Ц": 0x63,
           "Д": 0x64,
           "Е": 0x65,
           "Ф": 0x66,
           "Г": 0x67,
           "Х": 0x68,
           "И": 0x69,
           "Й": 0x6a,
           "К": 0x6b,
           "Л": 0x6c,
           "М": 0x6d,
           "Н": 0x6e,
           "О": 0x6f,
           "П": 0x70,
           "Я": 0x71,
           "Р": 0x72,
           "С": 0x73,
           "Т": 0x74,
           "У": 0x75,
           "Ж": 0x76,
           "В": 0x77,
           "Ь": 0x78,
           "Ы": 0x79,
           "З": 0x7a,
           "Ш": 0x7b,
           "Э": 0x7c,
           "Щ": 0x7d,
           "Ч": 0x7e
           }

from_koi7 = {v: k for k, v in to_koi7.items()}
