from .asm_parsers import *

r_codes = {"B": 0,
           "C": 1,
           "D": 2,
           "E": 3,
           "H": 4,
           "L": 5,
           "M": 6,
           "A": 7}

rp_codes = {"B": 0,
            "D": 1,
            "H": 2,
            "SP": 3,
            "PSW": 3}


codes = {"NOP": [lambda x: b"\x00", 1],
         "LXI": [lambda x: rp_d16(b"\x01", x), 3],
         "STAX": [lambda x: rp(b"\x02", x), 1],
         "INX": [lambda x: rp(b"\x03", x), 1],
         "INR": [lambda x: r3(b"\x04", x), 1],
         "DCR": [lambda x: r3(b"\x05", x), 1],
         "MVI": [lambda x: r3_d8(b"\x06", x), 2],
         "DAD": [lambda x: rp(b"\x09", x), 1],
         "LDAX": [lambda x: rp(b"\x0A", x), 1],
         "DCX": [lambda x: rp(b"\x0B", x), 1],
         "RLC": [lambda x: b"\x07", 1],
         "RRC": [lambda x: b"\x0F", 1],
         "RAL": [lambda x: b"\x17", 1],
         "RAR": [lambda x: b"\x1F", 1],
         "SHLD": [lambda x: d16(b"\x22", x), 3],
         "LHLD": [lambda x: d16(b"\x2A", x), 3],
         "STA": [lambda x: d16(b"\x32", x), 3],
         "LDA": [lambda x: d16(b"\x3A", x), 3],
         "DAA": [lambda x: b"\x27", 1],
         "CMA": [lambda x: b"\x2F", 1],
         "STC": [lambda x: b"\x37", 1],
         "CMC": [lambda x: b"\x3F", 1],
         "MOV": [lambda x: r3_r(b"\x40", x), 1],
         "HLT": [lambda x: b"\x76", 1],
         "ADD": [lambda x: r(b"\x80", x), 1],
         "ADC": [lambda x: r(b"\x88", x), 1],
         "SUB": [lambda x: r(b"\x90", x), 1],
         "SBB": [lambda x: r(b"\x98", x), 1],
         "ANA": [lambda x: r(b"\xA0", x), 1],
         "XRA": [lambda x: r(b"\xA8", x), 1],
         "ORA": [lambda x: r(b"\xB0", x), 1],
         "CMP": [lambda x: r(b"\xB8", x), 1],
         "ADI": [lambda x: d8(b"\xC6", x), 2],
         "ACI": [lambda x: d8(b"\xCE", x), 2],
         "SUI": [lambda x: d8(b"\xD6", x), 2],
         "SBI": [lambda x: d8(b"\xDE", x), 2],
         "ANI": [lambda x: d8(b"\xE6", x), 2],
         "XRI": [lambda x: d8(b"\xEE", x), 2],
         "ORI": [lambda x: d8(b"\xF6", x), 2],
         "CPI": [lambda x: d8(b"\xFE", x), 2],
         "RNZ": [lambda x: b"\xC0", 1],
         "RZ": [lambda x: b"\xC8", 1],
         "RNC": [lambda x: b"\xD0", 1],
         "RC": [lambda x: b"\xD8", 1],
         "RPO": [lambda x: b"\xE0", 1],
         "RPE": [lambda x: b"\xE8", 1],
         "RP": [lambda x: b"\xF0", 1],
         "RM": [lambda x: b"\xF8", 1],
         "RET": [lambda x: b"\xC9", 1],
         "JNZ": [lambda x: d16(b"\xC2", x), 3],
         "JZ": [lambda x: d16(b"\xCA", x), 3],
         "JNC": [lambda x: d16(b"\xD2", x), 3],
         "JC": [lambda x: d16(b"\xDA", x), 3],
         "JPO": [lambda x: d16(b"\xE2", x), 3],
         "JPE": [lambda x: d16(b"\xEA", x), 3],
         "JP": [lambda x: d16(b"\xF2", x), 3],
         "JM": [lambda x: d16(b"\xFA", x), 3],
         "JMP": [lambda x: d16(b"\xC3", x), 3],
         "CNZ": [lambda x: d16(b"\xC4", x), 3],
         "CZ": [lambda x: d16(b"\xCC", x), 3],
         "CNC": [lambda x: d16(b"\xD4", x), 3],
         "CC": [lambda x: d16(b"\xDC", x), 3],
         "CPO": [lambda x: d16(b"\xE4", x), 3],
         "CPE": [lambda x: d16(b"\xEC", x), 3],
         "CP": [lambda x: d16(b"\xF4", x), 3],
         "CM": [lambda x: d16(b"\xFC", x), 3],
         "CALL": [lambda x: d16(b"\xCD", x), 3],
         "OUT": [lambda x: d8(b"\xD3", x), 2],
         "IN": [lambda x: d8(b"\xDB", x), 2],
         "XTHL": [lambda x: b"\xE3", 1],
         "XCHG": [lambda x: b"\xEB", 1],
         "PCHL": [lambda x: b"\xE9", 1],
         "SPHL": [lambda x: b"\xF9", 1],
         "DI": [lambda x: b"\xF3", 1],
         "EI": [lambda x: b"\xFB", 1],
         "POP": [lambda x: rp(b"\xC1", x), 1],
         "PUSH": [lambda x: rp(b"\xC5", x), 1],
         "RST": [lambda x: rst(b"\xC7", x), 1]
         }

directives = {"ORG",
              "EQU",
              "END",
              "DB",
              "DW",
              "DS"}

koi7 = {"▘": b"\x01",
        "▝": b"\x02",
        "▀": b"\x03",
        "▗": b"\x04",
        "▚": b"\x05",
        "▐": b"\x06",
        "▜": b"\x07",
        "🧍": b"\x09",
        "↑": b"\x0b",
        "\n": b"\x0d",
        "→": b"\x0e",
        "↓": b"\x0f",
        "▖": b"\x10",
        "▌": b"\x11",
        "▞": b"\x12",
        "▛": b"\x13",
        "▄": b"\x14",
        "▙": b"\x15",
        "▟": b"\x16",
        "█": b"\x17",
        "|": b"\x1b",
        "—": b"\x1c",
        "←": b"\x1d",
        "🍏": b"\x1e",
        " ": b"\x20",
        "!": b"\x21",
        '"': b"\x22",
        "#": b"\x23",
        "$": b"\x24",
        "%": b"\x25",
        "&": b"\x26",
        "(": b"\x28",
        ")": b"\x29",
        "*": b"\x2a",
        "+": b"\x2b",
        ",": b"\x2c",
        "-": b"\x2d",
        ".": b"\x2e",
        "/": b"\x2f",
        "0": b"\x30",
        "1": b"\x31",
        "2": b"\x32",
        "3": b"\x33",
        "4": b"\x34",
        "5": b"\x35",
        "6": b"\x36",
        "7": b"\x37",
        "8": b"\x38",
        "9": b"\x39",
        ":": b"\x3a",
        ";": b"\x3b",
        "<": b"\x3c",
        "=": b"\x3d",
        ">": b"\x3e",
        "?": b"\x3f",
        "@": b"\x40",
        "A": b"\x41",
        "B": b"\x42",
        "C": b"\x43",
        "D": b"\x44",
        "E": b"\x45",
        "F": b"\x46",
        "G": b"\x47",
        "H": b"\x48",
        "I": b"\x49",
        "J": b"\x4a",
        "K": b"\x4b",
        "L": b"\x4c",
        "M": b"\x4d",
        "N": b"\x4e",
        "O": b"\x4f",
        "P": b"\x50",
        "Q": b"\x51",
        "R": b"\x52",
        "S": b"\x53",
        "T": b"\x54",
        "U": b"\x55",
        "V": b"\x56",
        "W": b"\x57",
        "X": b"\x58",
        "Y": b"\x59",
        "Z": b"\x5a",
        "[": b"\x5b",
        "\\": b"\x5c",
        "]": b"\x5d",
        "^": b"\x5e",
        "_": b"\x5f",
        "Ю": b"\x60",
        "А": b"\x61",
        "Б": b"\x62",
        "Ц": b"\x63",
        "Д": b"\x64",
        "Е": b"\x65",
        "Ф": b"\x66",
        "Г": b"\x67",
        "Х": b"\x68",
        "И": b"\x69",
        "Й": b"\x6a",
        "К": b"\x6b",
        "Л": b"\x6c",
        "М": b"\x6d",
        "Н": b"\x6e",
        "О": b"\x6f",
        "П": b"\x70",
        "Я": b"\x71",
        "Р": b"\x72",
        "С": b"\x73",
        "Т": b"\x74",
        "У": b"\x75",
        "Ж": b"\x76",
        "В": b"\x77",
        "Ь": b"\x78",
        "Ы": b"\x79",
        "З": b"\x7a",
        "Ш": b"\x7b",
        "Э": b"\x7c",
        "Щ": b"\x7d",
        "Ч": b"\x7e"
        }
